template = ""
rev_id = 3
template_sha = "50f983ed6da8e78c9c3344a18d6a46e3f843236c"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "sv"
__UND2C_TRG__ = "sma"
__UNDEFINED_SOURCE__ = "Swedish"
__UNDEFINED_TARGET__ = "South Sámi"
__UND_SRC__ = "swe"
__UND_TRG__ = "sma"
