template = ""
rev_id = 4
template_sha = "156a8b834dacf74fc905a1ee460fe5eabb9556c6"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "sv"
__UND2C_TRG__ = "sma"
__UNDEFINED_SOURCE__ = "Swedish"
__UNDEFINED_TARGET__ = "South Sámi"
__UND_SRC__ = "swe"
__UND_TRG__ = "sma"
