remote_theme: giellalt/jekyll-theme-giellalt@main
title: Dictionary for Swedish ⇒ South Saami
description: An electronic dictionary from Swedish to South Saami
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: minimal
